# Makefile
# Walk forward Arduino sketch
ARDUINO_DIR = /Applications/Arduino.app/Contents/Resources/Java
BOARD_TAG = atmega168
ARDUINO_PORT = /dev/tty.usbserial-*
ARDUINO_LIBS = ColorLED

include ../Arduino.mk
