ARDUINO_DIR = /Applications/Arduino.app/Contents/Resources/Java
ARDMK_DIR = /usr/local/share/arduino-mk

BOARD_TAG    = uno
MONITOR_PORT = /dev/tty.usbmodem*
ARDUINO_LIBS = 

include ${ARDMK_DIR}/Arduino.mk
