# Makefile
# Walk forward Arduino sketch
ARDUINO_DIR = /Applications/Arduino.app/Contents/Resources/Java
BOARD_TAG = atmega328
ARDUINO_PORT = /dev/tty.usbserial-*
ARDUINO_LIBS = IRremote

include ../Arduino.mk
